### ISSUE TITLE
I want to open a PR to eliminate all compilation warnings

### ISSUE THREAD

**Issue by Hentioe** [riverrun/not_qwerty123#14]
It may lead to higher minimum Elixir requirements (should be v1.11). Will it be merged?

**Comment by riverrun** [comment]
Maybe it will be easier if you tell me what what changes you would like made, and then I can look into adding them when upgrading the library to version 3.

**Comment by Hentioe** [comment]
I have already opened the PR, please check it out, thank you.

**Comment by Hentioe** [comment]
#15

**Comment by riverrun** [comment]
Thanks. I will get back to you soon about this.

**Comment by riverrun** [comment]
Added in d488a55
