### ISSUE TITLE
A way to configure minimum length of password or string

### ISSUE THREAD

**Issue by kathgironpe** [riverrun/not_qwerty123#2]
I'm thinking there should be a config variable and we can do `System.get_env("MIN_PASSWORD_LENGTH")`. 

Closing this. 
Can do:

`NotQwerty123.PasswordStrength.strong_password?("verylongpassword", [min_length: System.get_env("MIN_PASSWORD_LENGTH"), extra_chars: false])`

Thank you!

**Comment by riverrun** [comment]
Hi,
I'm sorry I didn't get back to you earlier. I'm glad you found out how to set the minimum length.
About the password length, I wouldn't recommend setting it below 8 characters if the password is protecting resources of any value. I know this makes passwords difficult to remember, but that is a fundamental problem with using passwords for authentication - easy to remember passwords are often easy to guess, which makes them weak.

**Comment by kathgironpe** [comment]
@riverrun yes, there's that security issue when it's below 8 characters but I believe more in locking account after 3 failed attempts. We only worry about brute force attacks. I am implementing all of these on every Phoenix app. I ended up using regular expression for validation. What I see this useful for: those apps that use SSO/ OAuth by default and you have to generate a default password for the user.
